## OS
FROM node:18-alpine as build

##  Install dependencies
RUN apk add --no-cache python3 py3-pip
RUN alias python=python3

RUN apk add git
RUN apk add openssh-keygen

RUN yarn global add npm@8

RUN npm install -g @vue/cli  --silent

# Creating work folder on root
WORKDIR /app





# COPY package.json ./
# RUN npm install

# Ideally, these files woudn't be in the git root, but we can work with that.
# COPY *.json /app/
# ADD src /app/src
# ADD public /app/public
# COPY *js /app/
# COPY .env /app/
# COPY .env.local /app/

# WORKDIR /app
# RUN npm run dev

